# Generated by Django 2.2 on 2020-06-22 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=False, max_length=264)),
                ('product_name', models.CharField(max_length=264)),
                ('product_url', models.URLField(blank=True)),
                ('product_image', models.URLField(blank=True)),
                ('product_price', models.FloatField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
